language: go

go:
    - 1.x

before_install:
    - go get github.com/mitchellh/gox
    - go get

install:
    - gox -osarch="darwin/amd64" -output="dist/{{.Dir}}-{{.OS}}-{{.Arch}}"
    - gox -osarch="linux/amd64" -output="dist/{{.Dir}}-{{.OS}}-{{.Arch}}"
  
script:
    - ls -l dist | grep imgcat

deploy:
    provider: releases
    token: "$GH_TOKEN"
    file: dist/*
    edge: true
    overwrite: true
    on:
        tags: true
